Classified/Controllers/AdvertsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Classified.DAL;
using Classified.Models;

namespace Classified.Controllers
{
    public class AdvertsController : Controller
    {
        private ClassifiedContext db = new ClassifiedContext();

        // GET: Adverts1
        public ActionResult Index()
        {
            var adverts = db.Adverts.Include(a => a.Category);
            return View(adverts.ToList());
        }

        // GET: Adverts1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Find(id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            var arg = advert.getImages();
            ViewBag.images = arg;
            return View(advert);
        }

        // GET: Adverts1/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategorySubCategoryName");
            return View();
        }

        // POST: Adverts1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Advert advert, FormCollection f)
        {
            
            string langu = f["lengu"];
            advert.BuyerPaymentOptions = f["BuyerPaymentOptions"];
            if (f["idFiles"] != "")
            {
                advert.images = f["idFiles"];
            }
            if(langu == "imprerial")
            {
                string feet = f["feet"]+" feet";
                string inchs = f["inches"] + " inches";
                string length = feet +" - " + inchs;
                advert.Length = length;
                advert.Size = length;
                if (Int32.Parse(f["feet"]) >0 && Int32.Parse(f["inches"])>0)
                {
                    ModelState["Size"].Errors.Clear();
                }
            }
            if (langu == "metric")
            {
                string cm = f["cm"] + " cm";
                advert.Length = cm;
                advert.Size = cm;
                if(Int32.Parse(f["cm"]) > 0)
                {
                    ModelState["Size"].Errors.Clear();
                }
            }
            if (ModelState.IsValid)
            {
                db.Adverts.Add(advert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategorySubCategoryName", advert.CategoryID);
            return View(advert);
        }

        // GET: Adverts1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Find(id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategorySubCategoryName", advert.CategoryID);
            return View(advert);
        }

        // POST: Adverts1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AdvertID,CategoryID,CanonicalUrl,Url,Headline,Length,Size,Price,Make,Model,Year,Description,Name,Phone,Email,Suburb,State,BuyerPaymentOptions,DeliveryOptions")] Advert advert)
        {
            if (ModelState.IsValid)
            {
                db.Entry(advert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategorySubCategoryName", advert.CategoryID);
            return View(advert);
        }

        // GET: Adverts1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Find(id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            return View(advert);
        }

        // POST: Adverts1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Advert advert = db.Adverts.Find(id);
            db.Adverts.Remove(advert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Upload()
        {
            var _path = "";
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var file = Request.Files[i];

                var fileName = System.IO.Path.GetFileName(file.FileName);
                _path = "~/Images/" + fileName;
                var path = System.IO.Path.Combine(Server.MapPath("~/Images"), fileName);
                file.SaveAs(path);


            }
            return Json(_path);
         }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Classified/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Classified</title>
    <!-- Bootstrap -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/dropzone.css" rel="stylesheet">
    <link href="~/Content/css/styles.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Classified", "Index", "Adverts", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Adverts", "Index", "Adverts")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Classified</p>
        </footer>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Content/Scripts/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/Content/Scripts/bootstrap.min.js"></script>
    <script src="~/Content/Scripts/dropzone.js"></script>
    <script src="~/Content/Scripts/jquery.validate.js"></script>
    <script src="~/Content/Scripts/scripts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>